# Generated by Django 4.0.2 on 2022-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_movies_age_limit_alter_movies_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
