# Generated by Django 4.0.2 on 2022-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
