# Generated by Django 4.0.2 on 2022-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
