# Generated by Django 4.0.2 on 2022-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_us_our_statistics_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='teams',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
