# Generated by Django 4.0.2 on 2022-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about_us_about_about_us_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Our_statistics',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='about',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='teams',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='our_statistics',
            field=models.IntegerField(),
        ),
    ]
