# Generated by Django 4.0.2 on 2022-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='media')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
