# Generated by Django 4.0.2 on 2022-05-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_sign_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={},
        ),
    ]
